### PR TITLE
support React 17

### PR DESCRIPTION
**Pull request by ah584d**

### CODE REVIEW

**Comment by ah584d** [comment]
PR upon issue
https://github.com/UdaySravanK/RNSwipeButton/issues/79

**Comment by tsejerome** [comment]
Is there any updates regarding this PR? And is there anyway I could help on this PR too? I wanna use this package at React 17!

**Comment by ah584d** [comment]
I'm afraid that it happened something bad to the repo's creator (hard covid maybe ?) - look at his profile he did not commit anything for more than 8 months!
I'm a contributor and I sent him many mails....without response. I have no write permissions to merge the PRs.
You will need to fork the repo and to maintain your own library - at this stage I don't see other solution.

**Comment by tsejerome** [comment]
Feeling bad about it, hope all the best to the creator...
Have you tried to ping him on LinkedIn too? (https://www.linkedin.com/in/uday-sravan-kamineni-65135321/)
One more question: will you be forking and publishing to npm tho?

I just tested updating the react peerDependencies to 17 and it feels like the swiping is not working at all at React 17!

**Review by UdaySravanK — APPROVED** [review]

**Comment by UdaySravanK** [comment]
Hi 👋🏻 I was on vacation for 2 months and out of station. Totally stayed away from computers. Apologies for all the trouble. I will publish a dot release soon to unblock your work. Thank you @ah584d for the PR. I appreciate it.

**Comment by ah584d** [comment]
happy to see back again :-)

**Comment by ah584d** [comment]
> Feeling bad about it, hope all the best to the creator... Have you tried to ping him on LinkedIn too? (https://www.linkedin.com/in/uday-sravan-kamineni-65135321/) One more question: will you be forking and publishing to npm tho?
> 
> I just tested updating the react peerDependencies to 17 and it feels like the swiping is not working at all at React 17😥

let me know if it does not work' I tested it in both android and iOS and it worked perfectly - please elaborate here if you still have some issues

**Comment by tsejerome** [comment]
Awesome, i will let you both know soon. And welcome back @UdaySravanK

**Pull request merged**
