### PR TITLE
FIX remove deprecated AccessibilityInfo.removeEventListener

### PR DESCRIPTION
**Pull request by ElpayetSupervan**
https://github.com/UdaySravanK/RNSwipeButton/issues/92

### CODE REVIEW

**Review by standbyskipper — APPROVED** [review]

**Comment by UdaySravanK** [comment]
Hi, I will review and test it ASAP, thanks for the PR.

**Review by narender56 — APPROVED** [review]
LGTM 👍🏻

**Comment by ElpayetSupervan** [comment]
Still in review ?

**Review by UdaySravanK — APPROVED** [review]
Tested it and changes look good. Thanks for the PR.

**Pull request merged**
